version: '3.1'
services:
    dashboard:
        build: .
        restart: always
        ports:
            - "8080:8080"
        command: >
            sh -c "flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0"